---
- name: Add the OSSEC APT key
  apt_key: url=http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key state=present

- name: Add the OSSEC source to the APT source list
  apt_repository: repo='deb http://ossec.wazuh.com/repos/apt/ubuntu trusty main' state=present

- name: Install OSSEC
  apt: name={{item}} state=latest
  with_items:
   - ossec-hids-agent

- name: Copy ssl cert
  template: src=eu-ossec-cert dest=/var/ossec/etc/sslmanager.cert

- name: Copy ssl keys
  template: src=eu-ossec-key dest=/var/ossec/etc/sslmanager.key

- name: Configure OSSEC
  template: src=ossec.conf dest=/var/ossec/etc/ossec.conf
  notify: Restart OSSEC

- name: Connect to ossec-server
  shell: /var/ossec/bin/agent-auth -m ossec.server.com -p 1515

- name: Restart OSSEC
  service: name={{item}} state=restarted
  with_items:
   - ossec

